apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noti-service
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/OrangesCloud/wealist-argo-helm.git 
    targetRevision: main
    path: main/helm/charts/noti-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-kind-local # 여기 수정 다른 브런치면
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
