apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-service
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/your-org/wealist-project-advanced.git
    targetRevision: main
    path: helm/charts/storage-service
    helm:
      valueFiles:
        - values.yaml
        - values-develop-registry-local.yaml
      parameters:
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
