apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/wealist-argo-helm
    targetRevision: dev
    path: helm/charts/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
