apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-apps
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/your-org/wealist-project-advanced.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
